displayName: Strip request cookies
type: middleware

import: github.com/pascal260303/stripcookie-regex

summary: 'Stripping request cookies by name'

testData:
  cookies:
    - cookieName
  cookieRegexes:
    - "^session_.*$"
